SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'shop-comp'
    AND TABLE_NAME = 'Receipt';

SELECT * FROM Receipt;

SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'shop-comp'
    AND TABLE_NAME = 'Shopper';

SELECT * FROM Shopper;

SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'shop-comp'
    AND TABLE_NAME = 'Store';

SELECT * FROM Store;


ALTER TABLE Receipt 
ADD CONSTRAINT SHOPPER_FK FOREIGN KEY (`shopper-uuid`) 
REFERENCES Shopper(`uuid`);

ALTER TABLE Receipt
ADD CONSTRAINT STORE_FK FOREIGN KEY (`store-uuid`) 
REFERENCES Store(`uuid`);
