SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'shop-comp'
    AND TABLE_NAME = 'Store';

SELECT * FROM Store;

SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'shop-comp'
    AND TABLE_NAME = 'Store Chain';
SELECT * FROM `Store Chain`;

ALTER TABLE Store
ADD CONSTRAINT STORE_CHAIN_FK FOREIGN KEY (`store-chain-uuid`)
REFERENCES `Store Chain`(`uuid`)
